### ISSUE TITLE
Address issue found in karma.conf.js [Opened by bitHound]

### ISSUE THREAD

**Issue by simonguo** [rsuite/rsuite-steps#1]
bitHound discovered 35 LintIssues in [karma.conf.js](https://github.com/rsuite/rsuite-steps/blob/51b619467dbc13688fe5ab105b6f159427c4e9ee/karma.conf.js). For details go to [bitHound](https://www.bithound.io/github/rsuite/rsuite-steps/blob/51b619467dbc13688fe5ab105b6f159427c4e9ee/karma.conf.js). 
***
Expected indentation of 2 space characters but found 4.

**Comment by Joey71** [comment]
Character indentation has been fixed.
